global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-exporter-1'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter-1:9100']

  - job_name: 'node-exporter-2'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter-2:9100']